print ("======== CACATAN BELANJA =======")
print ("======== Daftar 1 =========")
a = int(input("Daftar belanja 1: ['Sikat gigi', 'odol', 'shampo', 'sabun', 'ciduk'] "))
print ("======= Daftar belanja 2 ========")
a = int(input(" Daftar Belanja 2: ['Teh', 'Gula', 'Garam', 'Micin', 'Kecap'] "))
a= int(input(" Jawab dengan angka [1/2] "))
a= int(input(" 1. Rubah Belanjaan "))
a= int(input(" 2. Keluar "))
print (" Masukkan Pilihan: ")
print ("WRONG INPUT")
